localStorage.setItem("Абрикосы",41);
localStorage.setItem("Авокадо",197);
localStorage.setItem("Аджика",59);
localStorage.setItem("Айва",41);
localStorage.setItem("Айсберг",17);
localStorage.setItem("Активиа кефирная 1%",39);
localStorage.setItem("Ананас",50);
localStorage.setItem("Ананас консервированный",65);
localStorage.setItem("Ананас цукаты",78);
localStorage.setItem("Апельсин",43);
localStorage.setItem("Апельсиновый сок",44);
localStorage.setItem("Арахис",561);
localStorage.setItem("Арахис в сахаре",535);
localStorage.setItem("Базилик свежий",27);
localStorage.setItem("Баклажаны",27);
localStorage.setItem("Банан",97);
localStorage.setItem("Баранина вареная",286);
localStorage.setItem("Батон",264);
localStorage.setItem("Бедро индейки",143);
localStorage.setItem("Бекон",469);
localStorage.setItem("Блины обычные",178);
localStorage.setItem("Борщ лёгкий",58);
localStorage.setItem("Брокколи",33);
localStorage.setItem("Брусника",42);
localStorage.setItem("Бульон из говядины",57);
localStorage.setItem("Бульон из куриной грудки",42);
localStorage.setItem("Бульон куриный",33);
localStorage.setItem("Вареная говядина",236);
localStorage.setItem("Вареная колбаса",253);
localStorage.setItem("Вареная куриная грудка",138);
localStorage.setItem("Вареная курица",150);
localStorage.setItem("Вареная морковь",31);
localStorage.setItem("Вареная чечевица",111);
localStorage.setItem("Варёная сгущёнка",326);
localStorage.setItem("Вермишель",347);
localStorage.setItem("Ветчина",246);
localStorage.setItem("Вино белое сухое",67);
localStorage.setItem("Виноград",69);
localStorage.setItem("Вино красное сухое",70);
localStorage.setItem("Вишня",54);
localStorage.setItem("Геркулес",327);
localStorage.setItem("Говядина",192);
localStorage.setItem("Говяжья печень",110);
localStorage.setItem("Голень куриная",168);
localStorage.setItem("Голландский сыр",373);
localStorage.setItem("Голубика",46);
localStorage.setItem("Горбуша",143);
localStorage.setItem("Горох",256);
localStorage.setItem("Гороховое пюре",106);
localStorage.setItem("Горошек зеленый",59);
localStorage.setItem("Горчица",184);
localStorage.setItem("Гранат",67);
localStorage.setItem("Грейпфрут",41);
localStorage.setItem("Грецкие орехи",697);
localStorage.setItem("Гречневая каша рассыпчатая",131);
localStorage.setItem("Гречневая крупа",329);
localStorage.setItem("Грибы белые",28);
localStorage.setItem("Грибы белые сушеные",239);
localStorage.setItem("Грибы грузди",16);
localStorage.setItem("Грибы лисички",20);
localStorage.setItem("Грибы маслята",9);
localStorage.setItem("Грибы опята",17);
localStorage.setItem("Грибы подберёзовики свежие",17);
localStorage.setItem("Грибы подосиновики свежие",26);
localStorage.setItem("Грибы рыжики",17);
localStorage.setItem("Грибы шампиньоны",22);
localStorage.setItem("Груша",51);
localStorage.setItem("Груша (сухофрукты)",246);
localStorage.setItem("Дайкон",21);
localStorage.setItem("Джем мандариновый",276);
localStorage.setItem("Дрожжи",263);
localStorage.setItem("Дрожжи сухие",410);
localStorage.setItem("Дыня",35);
localStorage.setItem("Ежевика",31);
localStorage.setItem("Жареное яйцо",183);
localStorage.setItem("Желатин",343);
localStorage.setItem("Зеленая фасоль",30);
localStorage.setItem("Зеленый лук",19);
localStorage.setItem("Зелень петрушки",50);
localStorage.setItem("Зелёный горошек Бондюэль",60);
localStorage.setItem("Зелёный горошек Фрау Марта",40);
localStorage.setItem("Земляника",38);
localStorage.setItem("Зефир бело-розовый",304);
localStorage.setItem("Изюм",280);
localStorage.setItem("Имбирь свежий",72);
localStorage.setItem("Индейка (грудка)",94);
localStorage.setItem("Индейка (филе)",188);
localStorage.setItem("Инжир (сухофрукты)",239);
localStorage.setItem("Йогурт Активия",97);
localStorage.setItem("Кабачки жареные",91);
localStorage.setItem("Кабачки цукини",16);
localStorage.setItem("Кабачковая икра",90);
localStorage.setItem("Кабачок",28);
localStorage.setItem("Какао",234);
localStorage.setItem("Какао порошок",326);
localStorage.setItem("Кальмар",97);
localStorage.setItem("Кальмар вареный",103);
localStorage.setItem("Каперсы",21);
localStorage.setItem("Капуста белокочаная",28);
localStorage.setItem("Капуста белокочанная",29);
localStorage.setItem("Капуста брокколи замороженая",21);
localStorage.setItem("Капуста брюссельская",47);
localStorage.setItem("Капуста жареная",88);
localStorage.setItem("Капуста квашенная",23);
localStorage.setItem("Капуста китайская",16);
localStorage.setItem("Капуста кольраби",42);
localStorage.setItem("Капуста краснокочанная",29);
localStorage.setItem("Капуста морская",58);
localStorage.setItem("Капуста пекинская",15);
localStorage.setItem("Капуста цветная",34);
localStorage.setItem("Картофель",84);
localStorage.setItem("Картофель молодой",61);
localStorage.setItem("Картофельные хлопья",366);
localStorage.setItem("Картофель отварной",83);
localStorage.setItem("Картофель печеный",113);
localStorage.setItem("Картофель фри",323);
localStorage.setItem("Картошка",105);
localStorage.setItem("Каша рисовая",130);
localStorage.setItem("Квас хлебный",24);
localStorage.setItem("Кедровые орехи",652);
localStorage.setItem("Кетчуп",90);
localStorage.setItem("Кефир 1%",45);
localStorage.setItem("Кешью",607);
localStorage.setItem("Киви",51);
localStorage.setItem("Клубника",32);
localStorage.setItem("Клюква",43);
localStorage.setItem("Клюква сушеная",305);
localStorage.setItem("Козий сыр",296);
localStorage.setItem("Колбаса вареная докторская",254);
localStorage.setItem("Конфеты Батончики Рот Фронт с орехами",379);
localStorage.setItem("Корень имбиря",90);
localStorage.setItem("Корень сельдерея",31);
localStorage.setItem("Коричневый сахар",393);
localStorage.setItem("Корнишоны маринованные",36);
localStorage.setItem("Котлеты полтавские",415);
localStorage.setItem("Кофе молотый Арабика",193);
localStorage.setItem("Кофе растворимый (сухой)",116);
localStorage.setItem("Кофе эспрессо крепкий",19);
localStorage.setItem("Кофе якобз монарх (растворимый)",97);
localStorage.setItem("Крабовые палочки",85);
localStorage.setItem("Краковская колбаса",420);
localStorage.setItem("Красная фасоль консервированная",99);
localStorage.setItem("Крахмал картофельный",335);
localStorage.setItem("Крахмал кукурузный",348);
localStorage.setItem("Краюшка",226);
localStorage.setItem("Креветки (отварные)",90);
localStorage.setItem("Крупа гречневая",326);
localStorage.setItem("Крупа кукурузная",337);
localStorage.setItem("Крупа манная",330);
localStorage.setItem("Крупа овсяная",342);
localStorage.setItem("Крупа перловая",328);
localStorage.setItem("Крупа пшеничная",322);
localStorage.setItem("Крупа рис длиннозерный пропаренный",333);
localStorage.setItem("Крупа рисовая",330);
localStorage.setItem("Крупа ячневая",318);
localStorage.setItem("Крыжовник",41);
localStorage.setItem("Кукуруза консервированная",87);
localStorage.setItem("Кукурузные хлопья",353);
localStorage.setItem("Кунжут",562);
localStorage.setItem("Курага",232);
localStorage.setItem("Куриная печень",140);
localStorage.setItem("Куриные грудки",144);
localStorage.setItem("Куриные окорочка",170);
localStorage.setItem("Курица",186);
localStorage.setItem("Кус-Кус (крупа)",373);
localStorage.setItem("Лаваш грузинский",269);
localStorage.setItem("Лайм",20);
localStorage.setItem("Лапша гречневая",348);
localStorage.setItem("Лапша рисовая",350);
localStorage.setItem("Лапша яичная",330);
localStorage.setItem("Лимон",27);
localStorage.setItem("Лимонный сок",20);
localStorage.setItem("Лосось",172);
localStorage.setItem("Лук",40);
localStorage.setItem("Лук зелёный перо",16);
localStorage.setItem("Лук красный салатный",42);
localStorage.setItem("Льняное масло",849);
localStorage.setItem("Майонез",550);
localStorage.setItem("Майонез 15%",156);
localStorage.setItem("Майонез провансаль 67%",619);
localStorage.setItem("Мак",519);
localStorage.setItem("Макаронные изделия",344);
localStorage.setItem("Макароны отварные",119);
localStorage.setItem("Малина",41);
localStorage.setItem("Манго",62);
localStorage.setItem("Манго цукаты",278);
localStorage.setItem("Мандарин",40);
localStorage.setItem("Манная крупа",334);
localStorage.setItem("Маргарин молочный",745);
localStorage.setItem("Маргарин солнечный",653);
localStorage.setItem("Мармелад",302);
localStorage.setItem("Маслины",167);
localStorage.setItem("Маслины без косточки",133);
localStorage.setItem("Масло кукурузное",916);
localStorage.setItem("Масло льняное",895);
localStorage.setItem("Масло оливковое",851);
localStorage.setItem("Масло подсолнечное",864);
localStorage.setItem("Масло растительное",897);
localStorage.setItem("Масло сливочное",674);
localStorage.setItem("Масло топленое",890);
localStorage.setItem("Мед",315);
localStorage.setItem("Миндаль",601);
localStorage.setItem("Молоко",66);
localStorage.setItem("Молоко сгущёное",317);
localStorage.setItem("Молоко сухое",446);
localStorage.setItem("Морковь отварная",32);
localStorage.setItem("Морковь печеная",31);
localStorage.setItem("Морковь свежая",35);
localStorage.setItem("Мороженое Пломбир",245);
localStorage.setItem("Морская капуста",37);
localStorage.setItem("Мука кукурузная",333);
localStorage.setItem("Мука пшеничная в/с",332);
localStorage.setItem("Мука ржаная",307);
localStorage.setItem("Мюстли с фруктами",314);
localStorage.setItem("Мясо свинина",293);
localStorage.setItem("Мясо свинина постная",151);
localStorage.setItem("Нектарин",47);
localStorage.setItem("Облепиха",47);
localStorage.setItem("Овощная смесь “Весенние овощи”",30);
localStorage.setItem("Овсяная мука",368);
localStorage.setItem("Овсянка",271);
localStorage.setItem("Овсянные хлопья геркулес",305);
localStorage.setItem("Огурцы",19);
localStorage.setItem("Огурцы грунтовые",14);
localStorage.setItem("Огурцы маринованные",16);
localStorage.setItem("Огурцы солёные",14);
localStorage.setItem("Оливки",178);
localStorage.setItem("Оливки зеленые без косточки",157);
localStorage.setItem("Омлет",175);
localStorage.setItem("Орех грецкий",671);
localStorage.setItem("Отруби овсяные",305);
localStorage.setItem("Отруби пшеничные очищенные",214);
localStorage.setItem("Отруби ржаные очищенные",167);
localStorage.setItem("Паприка",112);
localStorage.setItem("Патиссон",19);
localStorage.setItem("Перепелиное яйцо",167);
localStorage.setItem("Перец сладкий",26);
localStorage.setItem("Перец чили",40);
localStorage.setItem("Перловка (крупа)",346);
localStorage.setItem("Перловка отварная",121);
localStorage.setItem("Персики",51);
localStorage.setItem("Персики (сухофрукты)",168);
localStorage.setItem("Петрушка корень",48);
localStorage.setItem("Петрушка свежая",38);
localStorage.setItem("Печенье Юбилейное Молочное",455);
localStorage.setItem("Печень куриная",144);
localStorage.setItem("Пиво светлое",42);
localStorage.setItem("Пиво тёмное",48);
localStorage.setItem("Плавленный сыр",280);
localStorage.setItem("Помидоры консервированные",23);
localStorage.setItem("Помидоры свежие",33);
localStorage.setItem("Простокваша",52);
localStorage.setItem("Пшено",337);
localStorage.setItem("Ревень черешковый",16);
localStorage.setItem("Редис",20);
localStorage.setItem("Редька",35);
localStorage.setItem("Редька зеленая",35);
localStorage.setItem("Репа",29);
localStorage.setItem("Рис",331);
localStorage.setItem("Рис отварной",134);
localStorage.setItem("Рожки отварные",115);
localStorage.setItem("Рожки (сухой продукт)",344);
localStorage.setItem("Руккола",24);
localStorage.setItem("Рыба скумбрия",187);
localStorage.setItem("Рыба треска",80);
localStorage.setItem("Рябина черноплодная",54);
localStorage.setItem("Ряженка",62);
localStorage.setItem("Салат лист",16);
localStorage.setItem("Сахар песок",396);
localStorage.setItem("Свежая капуста",25);
localStorage.setItem("Свежий укроп",38);
localStorage.setItem("Свекла",61);
localStorage.setItem("Свекла отварная",50);
localStorage.setItem("Свинина",304);
localStorage.setItem("Сельдерей",13);
localStorage.setItem("Сельдерей стебель",11);
localStorage.setItem("Сельдь атлантическая жирная",204);
localStorage.setItem("Семена тыквы неочищенные с солью",596);
localStorage.setItem("Семечки подсолнечные",583);
localStorage.setItem("Сладкая кукуруза в початках",124);
localStorage.setItem("Слива садовая",45);
localStorage.setItem("Сливки 10%",118);
localStorage.setItem("Сливки 20%",206);
localStorage.setItem("Сливки 22%",224);
localStorage.setItem("Сливки 33%",322);
localStorage.setItem("Смесь орехов и сухофруктов экзотик",466);
localStorage.setItem("Сметана 10 %",117);
localStorage.setItem("Сметана 15%",159);
localStorage.setItem("Сметана 20%",204);
localStorage.setItem("Сметана 30 %",291);
localStorage.setItem("Смородина красная",40);
localStorage.setItem("Смородина чёрная",41);
localStorage.setItem("Соевый соус",36);
localStorage.setItem("Сок апельсиновый",47);
localStorage.setItem("Сок грейпфрутовый",44);
localStorage.setItem("Сок лайма",22);
localStorage.setItem("Сок лимона",18);
localStorage.setItem("Сок лимонный",29);
localStorage.setItem("Сок мандарина",43);
localStorage.setItem("Сок свекольный",61);
localStorage.setItem("Сок томатный",21);
localStorage.setItem("Сок яблочный",44);
localStorage.setItem("Соленый огурец",14);
localStorage.setItem("Соус соевый",53);
localStorage.setItem("Соя",359);
localStorage.setItem("Спагетти отварные",223);
localStorage.setItem("Спагетти (сухой продукт)",344);
localStorage.setItem("Сухари панировочные",362);
localStorage.setItem("Сыворотка",22);
localStorage.setItem("Сыр 45%",336);
localStorage.setItem("Сыр 50% Сливочный",288);
localStorage.setItem("Сыр Адыгейский",224);
localStorage.setItem("Сыр гауда",350);
localStorage.setItem("Сыр Лёгкий",300);
localStorage.setItem("Сырок плавленный Дружба",178);
localStorage.setItem("Сыр российский",361);
localStorage.setItem("Сыр твердый",358);
localStorage.setItem("Тархун",41);
localStorage.setItem("Творог 0%",75);
localStorage.setItem("Творог 1%",82);
localStorage.setItem("Творог 10%",150);
localStorage.setItem("Творог 5 %",122);
localStorage.setItem("Творог 9%",153);
localStorage.setItem("Творожная масса с цукатами",349);
localStorage.setItem("Тесто дрожжевое",238);
localStorage.setItem("Тесто слоеное дрожжевое",356);
localStorage.setItem("Тесто слоёное бездрожжевое",335);
localStorage.setItem("Томат",27);
localStorage.setItem("Томатная паста помидорка",77);
localStorage.setItem("Томатный сок",25);
localStorage.setItem("Томаты (парниковые)",14);
localStorage.setItem("Томаты черри",17);
localStorage.setItem("Треска филе",78);
localStorage.setItem("Тушенка говядина высший сорт",213);
localStorage.setItem("Тыква",22);
localStorage.setItem("Укроп",38);
localStorage.setItem("Уксус столовый 6-7%",13);
localStorage.setItem("Урюк (сухофрукты)",213);
localStorage.setItem("Фарш говяжий",214);
localStorage.setItem("Фарш куриный",166);
localStorage.setItem("Фасоль",263);
localStorage.setItem("Фасоль Бондюэль",74);
localStorage.setItem("Фасоль стручковая",29);
localStorage.setItem("Фасоль стручковая замороженная",26);
localStorage.setItem("Фасоль Фрау Марта",92);
localStorage.setItem("Фасоль Фрау Марта в томатном соусе",86);
localStorage.setItem("Фасоль Фрау Марта Лобио",80);
localStorage.setItem("Фенхель",31);
localStorage.setItem("Филе куринное",114);
localStorage.setItem("Филе куриной грудки",109);
localStorage.setItem("Финики (сухофрукты)",280);
localStorage.setItem("Фруктоза",390);
localStorage.setItem("Фундук",665);
localStorage.setItem("Хлеб белый",254);
localStorage.setItem("Хлеб бородинский",210);
localStorage.setItem("Хлеб пшеничный",263);
localStorage.setItem("Хлеб ржаной",187);
localStorage.setItem("Хлебцы пшеничные",305);
localStorage.setItem("Хлопья кукурузные",373);
localStorage.setItem("Хлопья овсяные",308);
localStorage.setItem("Хрен",113);
localStorage.setItem("Хурма",65);
localStorage.setItem("Цветная капуста отварная",29);
localStorage.setItem("Цедра апельсина",36);
localStorage.setItem("Цедра лимона",28);
localStorage.setItem("Цукаты",224);
localStorage.setItem("Цукини",18);
localStorage.setItem("Черемша",37);
localStorage.setItem("Черешня",51);
localStorage.setItem("Черника",39);
localStorage.setItem("Чернослив (сухофрукты)",256);
localStorage.setItem("Чеснок",115);
localStorage.setItem("Чечевица зелёная",286);
localStorage.setItem("Чечевица красная",312);
localStorage.setItem("Шампиньоны",26);
localStorage.setItem("Шампиньоны замороженные",27);
localStorage.setItem("Шампиньоны резанные консервированные",16);
localStorage.setItem("Шелковица",52);
localStorage.setItem("Шиповник сушёный",253);
localStorage.setItem("Шоколад горький 75%",550);
localStorage.setItem("Шоколад горький 80%",527);
localStorage.setItem("Шоколад молочный",539);
localStorage.setItem("Шпинат",22);
localStorage.setItem("Щавель",25);
localStorage.setItem("Яблоки",60);
localStorage.setItem("Яблоки сушёные (сухофрукты)",269);
localStorage.setItem("Яйца",162);
